version: "3.8"

services:
  api-service:
    container_name: apiservice
    networks:
      - mynetwork
    volumes:
      - ./api-service:/application
    ports:
      - 3001:3001
      - 5555:5555
    build: ./api-service
    command: sh -c "npm install && npm run db:migrate && npm run start:local"
    working_dir: /application
    depends_on:
      - db
    environment:
      PORT: "3001"
      DATABASE_PASSWORD: postgres
      DATABASE_USERNAME: postgres
      DATABASE_NAME: api_service
      DATABASE_HOST: "db"
      DATABASE_PORT: 5432
      TOKEN_SECRET: anysecret
      STOCK_SERVICE_URL: "http://stock-service:3000"
      ENCRYPT_SALT_ROUNDS: 10

  stock-service:
    container_name: stockservice
    networks:
      - mynetwork
    volumes:
      - ./stock-service:/application
    ports:
      - 3000:3000
    build: ./stock-service
    command: sh -c "npm install && npm run start:local"
    working_dir: /application
    environment:
      PORT: "3000"
      STOCK_SERVICE_URL: "https://stooq.com"

  db:
    image: postgres:11-alpine
    networks:
      - mynetwork
    environment:
      POSTGRES_DB: api_service
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

    ports:
      - 5432:5432

    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=2000'
  

volumes:
  postgres:

networks:
  mynetwork:
    name: mynetwork