components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas:
        RegisterUserResponse:
            properties:
                token:
                    type: string
                email:
                    type: string
            required:
                - token
                - email
            type: object
            additionalProperties: false
        ErrorResult:
            properties:
                message:
                    type: string
            required:
                - message
            type: object
            additionalProperties: false
        RoleEnum:
            enum:
                - user
                - admin
            type: string
    securitySchemes: {}
info:
    title: api-service
    version: 1.0.0
    contact: {}
openapi: 3.0.0
paths:
    /v1/register:
        post:
            operationId: Register
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                anyOf:
                                    - {$ref: '#/components/schemas/RegisterUserResponse'}
                                    - {$ref: '#/components/schemas/ErrorResult'}
                '400':
                    description: ""
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResult'
                '404':
                    description: ""
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResult'
                '500':
                    description: ""
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResult'
            description: 'Register an user.'
            tags:
                - Register
            security: []
            parameters: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            properties:
                                role:
                                    $ref: '#/components/schemas/RoleEnum'
                                email:
                                    type: string
                            required:
                                - role
                                - email
                            type: object
servers:
    -
        url: 'https://localhost:3001/api-service/api'
